esphome:
    name: air-node-1
    friendly_name: air-node-1

esp32:
    board: esp32dev
    framework:
        type: arduino

mqtt:
    broker: !env_var MQTT_BROKER
    discovery_object_id_generator: device_name

ota:
    password: !secret ota_password

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    # fallback to hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: 'Air-Node-1 Fallback Hotspot'
        password: !secret node_hostspot_password

captive_portal:

logger:

i2c:
    sda: 21
    scl: 22
    scan: true
    id: bus_a

sensor:
    - platform: bme680
      temperature:
          name: 'BME680 Temperature'
          oversampling: 16x
          filters:
              - offset: -3.5
      pressure:
          name: 'BME680 Pressure'
      humidity:
          name: 'BME680 Humidity'
      gas_resistance:
          name: 'BME680 Gas Resistance'
      address: 0x77
      update_interval: 60s
